
crm_url_mappings = {
    'Ringy': 'https://app.ringy.com/api/public/leads/new-lead',
    'GoHighLevel': 'https://rest.gohighlevel.com/v1/contacts/',
    'Google Sheets': 'https://sheets.googleapis.com/v4/spreadsheets/',
    'Other': ''
}


state_mappings = {
    "GA": ["ga", "georgia"],
    "NY": ["ny", "new york", "new_york"],
    "TX": ["texas" ,"tx"],
    "CA": ["california","ca"],
    "FL": ["florida","fl"],
    "AK": ["alaska","ak"],
    "HI": ["hawaii","hi"],
    "OH": ["ohio","oh"],
    "VA": ["virginia", "va"],
    "IN": ["indiana", "in"],
    "MA": ["massachusetts","ma"],
    "PA": ["pennsylvania", "pa"],
    "AZ": ["arizona", "az"],
    "CO": ["colorado","co"],
    "NC": ["north carolina", "north_carolina", "nc"],
    "NJ": ["new jersey", "new_jersey", "nj"],
    "IL": ["illinois", "il"],
    "WA": ["washington","wa"],
    "MI": ["michigan","mi"],
    "OR": ["oregon","or"],
    "UT": ["utah", "ut"],
    "MO": ["missouri", "mo"],
    "MD": ["maryland", "md"],
    "TN": ["tennessee","tn"],
    "LA": ["louisiana", "la"],
    "AL": ["alabama", "al"],
    "MN": ["minnesota", "mn"],
    "ME": ["maine", "me"],
    "SC": ["south carolina", "south_carolina", "sc"],
    "MT": ["montana", "mt"],
    "IA": ["iowa", "ia"],
    "OK": ["oklahoma", "ok"],
    "NV": ["nevada", "nv"],
    "CT": ["connecticut", "ct"],
    "WI": ["wisconsin", "wi"],
    "NM": ["new mexico", "new_mexico", "nm"],
    "KY": ["kentucky", "ky"],
    "KS": ["kansas", "ks"],
    "DE": ["delaware", "de"],
    "WV": ["west virginia", "west_virginia", "wv"],
    "WY": ["wyoming", "wy"],
    "NH": ["new hampshire", "new_hampshire", "nh"],
    "NE": ["nebraska", "ne"],
    "VT": ["vermont", "vt"],
    "MS": ["mississippi", "ms"],
    "RI": ["rhode island", "rhode_island", "ri"],
    "ND": ["north dakota", "north_dakota", "nd"],
    "AR": ["arkansas", "ar"],
    "ID": ["idaho", "id"],
    "SD": ["south dakota", "south_dakota", "sd"]
    }