
crm_url_mappings = {
    'Ringy': 'https://app.ringy.com/api/public/leads/new-lead',
    'GoHighLevel': 'https://rest.gohighlevel.com/v1/contacts/',
    'Google Sheets': 'https://sheets.googleapis.com/v4/spreadsheets/',
    'Other': ''
}


state_mappings = {
    "Georgia": ["ga", "georgia"],
    "New York": ["ny", "new york", "new_york"],
    "Texas": ["texas" ,"tx"],
    "California": ["california","ca"],
    "Florida": ["florida","fl"],
    "Alaska": ["alaska","ak"],
    "Hawaii": ["hawaii","hi"],
    "Ohio": ["ohio","oh"],
    "Virginia": ["virginia", "va"],
    "Indiana": ["indiana", "in"],
    "Massachusetts": ["massachusetts","ma"],
    "Pennsylvania": ["pennsylvania", "pa"],
    "Arizona": ["arizona", "az"],
    "Colorado": ["colorado","co"],
    "North Carolina": ["north carolina", "north_carolina", "nc"],
    "New Jersey": ["new jersey", "new_jersey", "nj"],
    "Illinois": ["illinois", "il"],
    "Washington": ["washington","wa"],
    "Michigan": ["michigan","mi"],
    "Oregon": ["oregon","or"],
    "Utah": ["utah", "ut"],
    "Missouri": ["missouri", "mo"],
    "Maryland": ["maryland", "md"],
    "Tennessee": ["tennessee","tn"],
    "Louisiana": ["louisiana", "la"],
    "Alabama": ["alabama", "al"],
    "Minnesota": ["minnesota", "mn"],
    "Maine": ["maine", "me"],
    "South Carolina": ["south carolina", "south_carolina", "sc"],
    "Montana": ["montana", "mt"],
    "Iowa": ["iowa", "ia"],
    "Oklahoma": ["oklahoma", "ok"],
    "Nevada": ["nevada", "nv"],
    "Connecticut": ["connecticut", "ct"],
    "Wisconsin": ["wisconsin", "wi"],
    "New Mexico": ["new mexico", "new_mexico", "nm"],
    "Kentucky": ["kentucky", "ky"],
    "Kansas": ["kansas", "ks"],
    "Delaware": ["delaware", "de"],
    "West Virginia": ["west virginia", "west_virginia", "wv"],
    "Wyoming": ["wyoming", "wy"],
    "New Hampshire": ["new hampshire", "new_hampshire", "nh"],
    "Nebraska": ["nebraska", "ne"],
    "Vermont": ["vermont", "vt"],
    "Mississippi": ["mississippi", "ms"],
    "Rhode Island": ["rhode island", "rhode_island", "ri"],
    "North Dakota": ["north dakota", "north_dakota", "nd"],
    "Arkansas": ["arkansas", "ar"],
    "Idaho": ["idaho", "id"],
    "South Dakota": ["south dakota", "south_dakota", "sd"]
    }